import { registerEnumType } from '@nestjs/graphql';

export enum Direction {
	ASC = 1,
	DESC = -1,
}
registerEnumType(Direction, { name: 'Direction' });

/** error messages shared by all services, so web and mobile can match on them */
export enum Message {
	SOMETHING_WENT_WRONG = 'Something went wrong!',
	CREATE_FAILED = 'Create failed!',
	USED_NICK = 'This nick is already taken!',
	USED_PHONE = 'This phone number is already registered!',
	USED_BUSINESS_NO = 'This business number is already registered!',
	WRONG_LOGIN = 'Wrong nick or password!',
	BLOCKED_MEMBER = 'Your account has been blocked. Contact support.',
	TOKEN_NOT_EXIST = 'Bearer token is not provided!',
	NOT_AUTHENTICATED = 'You are not authenticated, please login first!',
	ONLY_SPECIFIC_ROLES_ALLOWED = 'Allowed only for members with specific roles!',
	AGENT_UNDER_REVIEW = 'Your agent account is under review. Usually within 24 hours.',
	AGENT_REJECTED = 'Your agent application was rejected',
	ACCOUNT_UNAVAILABLE = 'This account is no longer available.',
	SMS_FAILED = 'Could not send SMS. Please try again later.',
	OTP_TOO_MANY_REQUESTS = 'Too many code requests. Please try again later.',
	OTP_WAIT_BEFORE_RESEND = 'Please wait a minute before requesting a new code.',
	OTP_SENT = 'Verification code has been sent.',
	OTP_SENT_IF_REGISTERED = 'If this number is registered, a code has been sent.',
	OTP_EXPIRED = 'The code has expired. Please request a new one.',
	OTP_WRONG_CODE = 'Wrong code',
	OTP_VERIFIED = 'Phone number verified.',
	PHONE_NOT_VERIFIED = 'Please verify your phone number first.',
	RESET_TOKEN_INVALID = 'Invalid or expired reset token. Please start over.',
	PASSWORD_RESET_DONE = 'Password has been changed. Please log in again.',
	UPDATE_FAILED = 'Update failed!',
	NOTHING_TO_UPDATE = 'Nothing to update.',
	NO_DATA_FOUND = 'No data found!',
	WRONG_PASSWORD = 'Wrong password.',
	SAME_PASSWORD = 'The new password must be different from the current one.',
	INVALID_ID = 'Invalid id!',
	ADMIN_CANNOT_UPDATE_SELF = 'Admins cannot change their own account here.',
	ADMIN_CANNOT_UPDATE_ADMIN = 'Admin accounts cannot be changed here.',
	ONLY_AGENT_CAN_BE_REJECTED = 'Only agent applications can be rejected.',
	NO_FILE = 'Please attach an image.',
	PROVIDE_ALLOWED_FORMAT = 'Please provide jpg, jpeg, png or webp images!',
	INVALID_IMAGE = 'The file is not a valid image.',
	UPLOAD_FAILED = 'Upload failed!',
	CAR_IMAGES_AGENT_ONLY = 'Only agents can upload car photos.',
	CAR_SOLD_FINAL = 'A sold car cannot be changed.',
	CAR_HELD_BY_ADMIN = 'An admin put this car on hold',
	CAR_REMOVE_ONLY_DELETED = 'Only deleted cars can be removed permanently. Delete the car first.',
	CAR_HOLD_ONLY_LISTED = 'Only listed (active or paused) cars can be put on hold.',
	SELF_LIKE_DENIED = 'You cannot like yourself.',
	SELF_SUBSCRIPTION_DENIED = 'You cannot follow yourself.',
	ONLY_AGENTS_FOLLOWABLE = 'Only agents can be followed.',
	ALREADY_FOLLOWING = 'You already follow this agent.',
	NOT_FOLLOWING = 'You do not follow this agent.',
	FOLLOW_BLOCKED = 'You are not allowed to follow this agent (blocked by the agent).',
	FOLLOW_SEARCH_REQUIRED = 'Tell whose list you want: search.followerId or search.followingId.',
	OWN_CONTENT_LIKE_DENIED = 'You cannot like your own car or article.',
	LIKE_BLOCKED = 'You are not allowed to like this (blocked by the owner).',
	COMMENT_BLOCKED = 'You are not allowed to comment here (blocked by the owner).',
	ARTICLE_REMOVE_ONLY_DELETED = 'Only deleted articles can be removed permanently. Delete the article first.',
	ARTICLE_IMAGES_NOT_ALLOWED = 'Only agents and admins can upload article images.',
	ARTICLE_IMAGE_NOT_UPLOADED = 'The article image must be uploaded through CarZip first (POST /upload/image).',
	CAR_IMAGES_NOT_UPLOADED = 'Car photos must be uploaded through CarZip first (POST /upload/images).',
	TEST_DRIVE_NOT_AVAILABLE = 'Test drives are not available for this car.',
	TEST_DRIVE_OWN_CAR = 'You cannot request a test drive for your own car.',
	TEST_DRIVE_BLOCKED = 'You are not allowed to request a test drive here (blocked by the agent).',
	TEST_DRIVE_DATE_INVALID = 'Pick a date and time in the future, within the next 60 days.',
	TEST_DRIVE_ALREADY_OPEN = 'You already have an open test drive for this car.',
	TEST_DRIVE_TOO_MANY_OPEN = 'You have too many open test-drive requests. Wait for answers or cancel some.',
	TEST_DRIVE_STATUS_DENIED = 'This test drive cannot be changed to that status now.',
	TEST_DRIVE_DATE_PASSED = 'The test drive date has passed.',
	TEST_DRIVE_NOT_YET = 'A test drive can be marked complete only after its date.',
	TEST_DRIVE_CAR_NOT_ACTIVE = 'This car is no longer on sale.',
}
